spring:
  application:
    name: Order Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/order_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true'
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL8Dialect은 deprecated됨
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true  # 개발 중에는 true로 설정 권장
        format_sql: true

server:
  port: 8083

product-service:
  api-url: http://localhost:8082/api/products

point-service:
  api-url: http://localhost:8084/api/points

logging:
  level:
    root: info

